# 由于两个容器中 共享同一个卷
#【nginx 容器中的 /var/log/nginx目录】 和 【busybox容器中 /var/log/busybox/nginx 目录 】，两者目录下的内容相同
# https://kubernetes.io/zh/docs/concepts/storage/volumes/#hostpath
# pod被删除后数据还会在
apiVersion: v1
kind: Pod
metadata:
  name: volume-pod-test-volumes-host-path
  labels:
    app: volume-pod-test-volumes-host-path
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: app-logs
          mountPath: /var/log/nginx
  volumes:
    - name: app-logs
      hostPath:
        # 宿主上目录位置，这里要使用绝对路径，试了下相对路径
        path: /Users/zxz/code/k8s/testMinikub/volume/hostPathShare
        type: DirectoryOrCreate